
# mybatis
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.zjh.usercenter.mybatis.entity
  configuration:
    map-underscore-to-camel-case: false

# cause mysql use camel name way so this config need to be setted to false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: flag
      logic-delete-value: 1 # 逻辑已被删除默认为1
      logic-not-delete-value: 0 # 逻辑未被删除逻辑为0

# backend server -- set
server:
  port: 8080
  reactive:
    session:
      timeout: 86400
  servlet:
    context-path: /api # 加上统一的路径/api
# spring config
# name -- project name
# datasource: mysql config
spring:
  application:
    name: user-center-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 199973
    url: jdbc:mysql://localhost:3306/uc_db
