
# mybatis
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.zjh.backend.mybatis.entity
  configuration:
    map-underscore-to-camel-case: false

# cause mysql use camel name way so this config need to be setted to false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: flag
      logic-delete-value: 1 # logic value has been removed : 1
      logic-not-delete-value: 0 # 逻辑未被删除逻辑为0 logic value has been not removed : 0

# backend server -- set
server:
  port: 8080
  reactive:
    session:
      timeout: 86400
#  servlet:
#    context-path: /api # 加上统一的路径/api : add union path : /api
# spring config
# name -- project name
# datasource: mysql config
spring:
  application:
    name: bi-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 199973
    url: jdbc:mysql://localhost:3306/bi_db
  # 配置redis信息
  redis:
    database: 1
    host: localhost
    timeout: 5000
    password:  123456
    port: 6379
#    添加apikey
yuapi:
  client:
    access-key: ractjchlw7y4hu0jb7yzqfy1f2qbtehw
    secret-key: 4tynhkovjqy5tmgrsj52xrxrs34s4npi

threadpool:
  param:
    core-pool-size: 4
    maximum-pool-size: 20
    keep-alive-time: 50
